In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\Dell\OneDrive\Desktop\Water_fault_ditection\artifacts\wafer.csv")

In [3]:
df.head()

,Unnamed: 0,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,...,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590,Good/Bad
0,Wafer-801,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,...,NaN,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876,-1
1,Wafer-802,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,...,NaN,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876,1
2,Wafer-803,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,...,NaN,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876,-1
3,Wafer-804,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,...,NaN,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876,-1
4,Wafer-805,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,...,NaN,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876,-1

In [4]:
X = df.drop(['Unnamed: 0','Good/Bad'],axis=1)
y = df[['Good/Bad']]

In [5]:
X.isna().sum()[X.isna().sum()>0]

Sensor-1       1
Sensor-3       3
Sensor-4       3
Sensor-5       3
Sensor-6       3
              ..
Sensor-570     3
Sensor-579    66
Sensor-580    66
Sensor-581    66
Sensor-582    66
Length: 167, dtype: int64

In [6]:
X.columns[X.isna().sum()>0]

Index(['Sensor-1', 'Sensor-3', 'Sensor-4', 'Sensor-5', 'Sensor-6', 'Sensor-7',
       'Sensor-8', 'Sensor-41', 'Sensor-42', 'Sensor-54',
       ...
       'Sensor-565', 'Sensor-566', 'Sensor-567', 'Sensor-568', 'Sensor-569',
       'Sensor-570', 'Sensor-579', 'Sensor-580', 'Sensor-581', 'Sensor-582'],
      dtype='str', length=167)

In [7]:
miss_col = X.columns[X.isna().sum()>0]

In [8]:
X.fillna(0,inplace=True)

,Sensor-1,Sensor-2,Sensor-3,Sensor-4,Sensor-5,Sensor-6,Sensor-7,Sensor-8,Sensor-9,Sensor-10,...,Sensor-581,Sensor-582,Sensor-583,Sensor-584,Sensor-585,Sensor-586,Sensor-587,Sensor-588,Sensor-589,Sensor-590
0,2968.33,2476.58,2216.7333,1748.0885,1.1127,100.0,97.5822,0.1242,1.5300,-0.0279,...,0.0,0.0,0.5004,0.0120,0.0033,2.4069,0.0545,0.0184,0.0055,33.7876
1,2961.04,2506.43,2170.0666,1364.5157,1.5447,100.0,96.7700,0.1230,1.3953,0.0084,...,0.0,0.0,0.4994,0.0115,0.0031,2.3020,0.0545,0.0184,0.0055,33.7876
2,3072.03,2500.68,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.3896,0.0138,...,0.0,0.0,0.4987,0.0118,0.0036,2.3719,0.0545,0.0184,0.0055,33.7876
3,3021.83,2419.83,2205.7445,1363.1048,1.0518,100.0,101.8644,0.1220,1.4108,-0.0046,...,0.0,0.0,0.4934,0.0123,0.0040,2.4923,0.0545,0.0184,0.0055,33.7876
4,3006.95,2435.34,2189.8111,1084.6502,1.1993,100.0,104.8856,0.1234,1.5094,-0.0046,...,0.0,0.0,0.4987,0.0145,0.0041,2.8991,0.0545,0.0184,0.0055,33.7876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3013.66,2526.44,2185.2111,1141.6306,0.8447,100.0,100.5978,0.1217,1.5337,0.0090,...,0.0,0.0,0.5013,0.0076,0.0021,1.5152,0.0153,0.0048,0.0017,31.0176
96,2982.87,2477.01,2315.2667,2360.1325,1.1259,100.0,90.1144,0.1160,1.4695,0.0071,...,0.0,0.0,0.5003,0.0106,0.0028,2.1263,0.0153,0.0048,0.0017,31.0176
97,3084.82,2387.42,2171.5000,1028.4440,0.7899,100.0,101.5122,0.1224,1.3603,-0.0031,...,0.0,0.0,0.5016,0.0130,0.0028,2.5865,0.0153,0.0048,0.0017,31.0176
98,2955.87,2541.89,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,1.4493,-0.0194,...,0.0,0.0,0.5023,0.0140,0.0033,2.7810,0.0153,0.0048,0.0017,31.0176
99,2914.86,2465.11,2210.2778,2120.5760,1.0700,100.0,95.1089,0.1230,1.5817,0.0118,...,0.0,0.0,0.5026,0.0121,0.0032,2.4064,0.0153,0.0048,0.0017,31.0176

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold,train_test_split,cross_val_score

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=20,random_state=42)

In [11]:
import os
os.getcwd()
os.chdir(r'C:\Users\Dell\OneDrive\Desktop\Water_fault_ditection')

In [12]:
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)
import pickle
with open("artifacts/scalar.pkl", "wb") as file:
    pickle.dump(scalar, file)

In [13]:
X_train_scaled

array([[-8.69156196,  0.56674638,  0.12581202, ..., -0.0353315 ,
        -0.27656638,  0.63796517],
       [ 0.69939206, -1.51844718,  0.12243354, ..., -0.88051638,
        -0.96933539, -0.87918336],
       [-0.08588657,  0.45676626,  0.121307  , ...,  0.17250085,
         0.50279876, -0.36190836],
       ...,
       [ 0.05816086,  0.38177311,  0.2229571 , ..., -0.09075346,
        -0.10337413, -0.46846294],
       [ 0.07489497,  1.15975329,  0.18974947, ...,  0.1032234 ,
         0.11311619,  0.07703884],
       [ 0.28412963,  0.57545622,  0.11503251, ..., -0.25701934,
        -0.49305669, -0.50359727]], shape=(80, 590))

In [14]:
y_train

    Good/Bad
55        -1
88        -1
26        -1
42        -1
69        -1
..       ...
60        -1
71        -1
14        -1
92        -1
51        -1

[80 rows x 1 columns]

In [15]:
from sklearn.ensemble import RandomForestClassifier
! pip install xgboost --quiet
from xgboost import XGBClassifier

In [16]:
y_train['Good/Bad'].unique()

array([-1,  1])

In [17]:
y_train['Good/Bad']=y_train['Good/Bad'].map({-1:0,1:1})
y_test['Good/Bad']=y_test['Good/Bad'].map({-1:0,1:1})

In [18]:
model1 = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
model2 = RandomForestClassifier(
    n_estimators=100,
    criterion="gini",
    max_depth=None,
    random_state=42
)

In [19]:
def model_trainer(model):
    # Stratified K-Fold Cross Validation
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(
        model,
        X_train_scaled,
        y_train,
        cv=skf,
        scoring='accuracy'
    )
    
    print("Cross Validation Results")
    print(f"CV Scores      : {cv_scores}")
    print(f"Mean Accuracy  : {cv_scores.mean():.4f}")
    print(f"Std Deviation  : {cv_scores.std():.4f}")
    print("-" * 40)

    model.fit(X_train_scaled,y_train)
    y_pred = model.predict(X_test)
    from sklearn.metrics import accuracy_score, classification_report
    acc = accuracy_score(y_test,y_pred)
    cls = classification_report(y_test,y_pred)
    print("Model Performance")
    print(f'Accuracy is :- {acc:.4f}')
    print('-'*40)
    print(f'Classsification Report')
    print(cls)

In [20]:
model_trainer(model1)

Cross Validation Results
CV Scores      : [0.9375 0.9375 0.9375 0.9375 0.875 ]
Mean Accuracy  : 0.9250
Std Deviation  : 0.0250
----------------------------------------
Model Performance
Accuracy is :- 1.0000
----------------------------------------
Classsification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

In [21]:
model_trainer(model2)

Cross Validation Results
CV Scores      : [0.9375 0.9375 0.9375 0.9375 0.875 ]
Mean Accuracy  : 0.9250
Std Deviation  : 0.0250
----------------------------------------
Model Performance
Accuracy is :- 0.8500
----------------------------------------
Classsification Report
              precision    recall  f1-score   support

           0       1.00      0.85      0.92        20
           1       0.00      0.00      0.00         0

    accuracy                           0.85        20
   macro avg       0.50      0.42      0.46        20
weighted avg       1.00      0.85      0.92        20

In [22]:
with open("artifacts/model.pkl", "wb") as file:
    pickle.dump(model1, file)

In [23]:
os.getcwd()

'C:\\Users\\Dell\\OneDrive\\Desktop\\Water_fault_ditection'

In [24]:
test_file = df.sample(5)

In [25]:
test_file.to_csv("artifacts/test_file.csv")